blog_backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('core.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from core.views import home_view, post_detail_view, contact_view, register_view, login_view,logout_view

app_name = 'core'

urlpatterns = [
    path('', home_view, name='home_view'),
    path('post/<int:post_id>/', post_detail_view, name='post_detail'),
    path('contact/', contact_view, name='contact'),
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

core/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=255)
    sub_title = models.CharField(max_length=255)
    content = models.TextField()
    post_by = models.CharField(max_length=255)
    is_activate = models.BooleanField(default=True)
    post_image = models.ImageField(upload_to='post_images/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title



class ContactUs(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=255)
    message = models.TextField()


    def __str__(self):
        return self.name

core/forms.py
from django import forms
from core.models import ContactUs
from django.contrib.auth.models import User




class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = ['name', 'email', 'phone', 'message']


class UserForm(forms.ModelForm):
    password_confirm = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'password_confirm']
        widgets = {
            'password': forms.PasswordInput(),
        }

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirm = cleaned_data.get("password_confirm")

        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError("Passwords do not match.")


    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput())

core/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.html import strip_tags

from core.models import Post
from core.forms import ContactForm, UserForm, LoginForm
from blog_backend.settings import EMAIL_HOST_USER,BASE_DIR

@login_required(login_url='core:login')
def home_view(request):
    posts = Post.objects.filter(is_activate=True)
    return render(request, 'home.html', {'posts': posts})


def post_detail_view(request, post_id):
    post = Post.objects.get(id=post_id)
    return render(request, 'post_detail.html', {'post': post})


def contact_view(request):
    form = ContactForm()
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            context = {
                "receiver_name": "Saium Khan",
                "age": 27,
                "profession": "Software Developer",
                "marital_status": "Divorced",
                "address": "Planet Earth",
                "year": 2023
            }
            template_name = f"{BASE_DIR}/templates/mail.html"
            convert_to_html_content = render_to_string(
                template_name=template_name,
                context=context
            )
            plain_message = strip_tags(convert_to_html_content)
            send_mail("Test Subject",
                      plain_message,
                      EMAIL_HOST_USER,
                      ["cavidan.mahmudoglu@gmail.com", "behbudovbehbud397@gmail.com"],
                      html_message=convert_to_html_content,
                      fail_silently=True)
            return render(request, 'contact.html', {"form": form, 'is_success': True})
        else:
            print(form.errors)
            return render(request, 'contact.html', {"form": form, 'is_success': False})

    return render(request, 'contact.html', {"form": form, 'is_success': False})



def register_view(request):
    form = UserForm()
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('core:login')
        else:
            print(form.errors)
            return render(request, 'register.html', {"form": form})

    return render(request, 'register.html', {"form": form})


def login_view(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('core:home_view')
            else:
                form.add_error(None, "Invalid username or password.")
                return render(request, 'login.html', {"form": form})

    return render(request, 'login.html', {"form": form})


def logout_view(request):
    logout(request)
    return redirect('core:login')

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="{% static 'base_site/assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'base_site/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'core:home_view' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="#">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'core:contact' %}">Contact</a></li>
                       {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'core:logout' %}">Logout</a></li>
                        {% else %}
                         <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'core:register' %}"><b style="color: black">Register</b></a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'core:login' %}"><b style="color: black">Login</b></a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('{% static 'base_site/assets/img/home-bg.jpg' %}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Clean Blog</h1>
                            <span class="subheading">A Blog Theme by Start Bootstrap</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        {% block content %}{% endblock %}



            <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'base_site/js/scripts.js' %}"></script>
    </body>
</html>

templates/contact.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}Contact{% endblock %}

{% block content %}
<!-- Main Content-->
<main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        {% if is_success %}

                                    <div class="text-center mb-3">
                                        <div class="fw-bolder">Form submission successful!</div>
                                        To activate this form, sign up at
                                        <br />
                                        <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                                    </div>
                                {% endif %}
                        {% if not is_success %}
                        <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
                        <div class="my-5">

                            <form id="contactForm" data-sb-form-api-token="API_TOKEN" method="POST">
                                {% csrf_token %}
                                <div class="form-floating">
                                    {% render_field form.name class="form-control"  %}
<!--                                    <input class="form-control" id="name" type="text" placeholder="Enter your name..." data-sb-validations="required" />-->
                                    <label for="name">Name</label>
                                    <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                                </div>
                                <div class="form-floating">
                                    {% render_field form.email class="form-control"  %}
<!--                                    <input class="form-control" id="email" type="email" placeholder="Enter your email..." data-sb-validations="required,email" />-->
                                    <label for="email">Email address</label>
<!--                                    <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>-->
<!--                                    <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>-->
                                </div>
                                <div class="form-floating">
                                    {% render_field form.phone class="form-control"  %}
<!--                                    <input name="phone" class="form-control" id="phone" type="tel" placeholder="Enter your phone number..." data-sb-validations="required" />-->
                                    <label for="phone">Phone Number</label>
<!--                                    <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>-->
                                </div>
                                <div class="form-floating">
                                    {% render_field form.message class="form-control"  %}
<!--                                    <textarea class="form-control" id="message" placeholder="Enter your message here..." style="height: 12rem" data-sb-validations="required"></textarea>-->
                                    <label for="message">Message</label>
<!--                                    <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>-->
                                </div>
                                <br />
                                <!-- Submit success message-->
                                <!---->
                                <!-- This is what your users will see when the form-->
                                <!-- has successfully submitted-->
                                <!-- Submit error message-->
                                <!---->
                                <!-- This is what your users will see when there is-->
                                <!-- an error submitting the form-->
                                <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                                <!-- Submit Button-->
                                <button class="btn btn-primary text-uppercase" id="submitButton" type="submit">Send</button>
                            </form>

                        </div>
                         {% endif %}
                    </div>
                </div>
            </div>
        </main>
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<!-- Main Content-->
<div class="container px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <!-- Post preview-->
      {% for post in posts %}
      <div class="post-preview">
        <a href="{% url 'core:post_detail' post.id %}">
          <h2 class="post-title">{{ post.title }}</h2>
          <h3 class="post-subtitle">{{post.sub_title}}</h3>
        </a>
        <p class="post-meta">
          Posted by
          <a href="{% url 'core:post_detail' post.id %}">{{post.post_by}}</a>
          {{post.created_at}}
        </p>
      </div>
      <!-- Divider-->
      <hr class="my-4"/>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
  <h1>Welcome to my website!</h1>
  <p>This is a paragraph.</p>
  <p>Click or double-click me to see the text change.</p>
  <script>
    const h1 = document.querySelector('h1');
    const p = document.querySelector('p');

    h1.addEventListener('click', () => {
      h1.textContent = 'Hello, World!';
    });

    p.addEventListener('dblclick', () => {
      p.textContent = 'This is a new paragraph.';
    });
  </script>
</body>
</html>

templates/login.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}Login{% endblock %}

{% block content %}
<!-- Main Content-->
<main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="my-5">
                            <form id="contactForm" data-sb-form-api-token="API_TOKEN" method="POST">
                                {% csrf_token %}
                                <div class="form-floating">
                                    <p style="color: red">{{ form.name.errors }}</p>
                                </div>
                                {{ form.as_p }}
                                <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                                <!-- Submit Button-->
                                <button class="btn btn-primary text-uppercase" id="submitButton" type="submit">Send</button>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </main>
{% endblock %}

templates/mail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <style>
        /* Inline CSS */
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
        }

        .email-container {
            width: 100%;
            max-width: 600px;
            margin: 0 auto;
            background-color: #ffffff;
            border: 1px solid #dddddd;
            border-radius: 5px;
        }

        .header {
            background-color: #007bff;
            color: #ffffff;
            text-align: center;
            padding: 20px;
        }

        .content {
            padding: 20px;
        }

        .image {
            max-width: 100%;
            height: auto;
        }

        .footer {
            background-color: #f0f0f0;
            text-align: center;
            padding: 10px;
            font-size: 12px;
        }
    </style>
</head>
<body>
    <div class="email-container">
        <div class="header">
            <h1>This Email is sent from Django project</h1>
        </div>
        <div class="content">
            <p>Hello {{ receiver_name }},</p>
            <p>This is a sample email template for Medium article.</p>
            <p> Your Age is: {{ age }} </p>
            <img src=" static 'your/static/file/path'" alt="static image">
            <img src="https://codeskulptor-demos.commondatastorage.googleapis.com/GalaxyInvaders/back01.jpg" alt="Image 3" class="image">
            <p>Your Profession: {{ profession }}</p>
            <p> You are: {{ marital_status }}</p>
            <p>Your address: {{ address }}</p>
        </div>
        <div class="footer">
            &copy; {{ year }} ABC Inc. No rights reserved.
        </div>
    </div>
</body>
</html>

templates/post_detail.html
{% extends "base.html" %}

{% block title %}Post Detail{% endblock %}

{% block content %}
<!-- Post Content-->
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>{{ post.content }}</p>
                    </div>
                </div>
            </div>
        </article>
{% endblock %}

templates/register.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}Register{% endblock %}

{% block content %}
<!-- Main Content-->
<main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="my-5">
                            <form id="contactForm" data-sb-form-api-token="API_TOKEN" method="POST">
                                {% csrf_token %}
                                <div class="form-floating">
                                    <p style="color: red">{{ form.name.errors }}</p>
                                </div>
                                {{ form.as_p }}
                                <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                                <!-- Submit Button-->
                                <button class="btn btn-primary text-uppercase" id="submitButton" type="submit">Send</button>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </main>
{% endblock %}